---
version: '3.7'

services:
  hello-app:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    container_name: hello-app
    restart: always
    ports:
      - "8883:8883/tcp"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M